#!/usr/bin/env python3
"""Generate English *.md from Indonesian *_id.md using phrase replacements."""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Order matters: longer phrases first.
REPLACEMENTS: list[tuple[str, str]] = [
    ("# Sequence: Buat Website", "# Sequence: Create Website"),
    ("# Sequence: Hapus Website", "# Sequence: Delete Website"),
    ("Membuat entri website baru: validasi → simpan DB → provision nginx config → optional enable + reload.",
     "Create a new website entry: validate → save DB → provision nginx config → optional enable + reload."),
    ("## GoSite (implementasi saat ini)", "## GoSite (current implementation)"),
    ("## GoSite (implementasi)", "## GoSite (implementation)"),
    ("(referensi migrasi)", "(migration reference)"),
    ("Diagram startup Laravel (historis)", "Historical Laravel startup diagram"),
    ("Diagram alur fitur GoSite.", "GoSite feature flow diagrams."),
    ("Bagian **Legacy BangunSite** (jika ada) disimpan sebagai referensi migrasi.",
     "**Legacy BangunSite** sections (if any) are kept as migration reference."),
    ("Bagian **Legacy BangunSite**", "**Legacy BangunSite** sections"),
    ("disimpan sebagai referensi migrasi.", "are kept as migration reference."),
    ("Proses saat container", "What happens when the container"),
    ("pertama kali (atau restart) dijalankan.", "starts (first boot or restart)."),
    ("### Proses runtime", "### Runtime processes"),
    ("GoSite **tidak** memakai binary `server-proxy` terpisah seperti BangunSite legacy. Panel dilayani oleh kombinasi **nginx edge** + **gosite serve**.",
     "GoSite **does not** use a separate `server-proxy` binary like legacy BangunSite. The panel is served by **nginx edge** + **gosite serve**."),
    ("Toggle website aktif dengan symlink antara `site.d` dan `active.d`, lalu nginx memuat vhost aktif.",
     "Toggle active website via symlink between `site.d` and `active.d`, then nginx loads active vhosts."),
    ("Dua jalur: **Certbot otomatis** (job + SSE) dan **upload manual**.",
     "Two paths: **automatic Certbot** (job + SSE) and **manual upload**."),
    ("Browse dan manipulasi file dalam **allowlist root**.",
     "Browse and manipulate files within **allowlisted roots**."),
    ("Kelola container via **Docker Engine API**", "Manage containers via **Docker Engine API**"),
    ("Kelola `/etc/fstab`", "Manage `/etc/fstab`"),
    ("Entities and filesystem file yang harus dipahami backend Go.",
     "Entities and filesystem artifacts the Go backend must understand."),
    ("Mapping route legacy ke usulan API REST untuk backend Go. Format respons JSON; error konsisten:",
     "Legacy route mapping to the proposed Go REST API. JSON responses; consistent errors:"),
    ("Pembagian paket dan status migrasi Laravel → Go.",
     "Package layout and Laravel → Go migration status."),
    ("Dokumen pendukung migrasi BangunSite → GoSite.",
     "Migration support documents for BangunSite → GoSite."),
    ("| Catatan |", "| Notes |"),
    ("| Kolom | Tipe | Keterangan |", "| Column | Type | Notes |"),
    ("| Perintah | Keterangan |", "| Command | Notes |"),
    ("| Method | Path | Keterangan |", "| Method | Path | Notes |"),
    ("| Legacy | Method | Usulan GoSite |", "| Legacy | Method | GoSite |"),
    ("| Path publik | Handler | Catatan |", "| Public path | Handler | Notes |"),
    ("| Env | Default | Peran |", "| Env | Default | Role |"),
    ("| File | Peran |", "| File | Role |"),
    ("| Path | Peran |", "| Path | Role |"),
    ("| Path | Isi |", "| Path | Contents |"),
    ("| Method | Path | Fungsi |", "| Method | Path | Purpose |"),
    ("| type | Perilaku |", "| type | Behavior |"),
    ("| Gejala | Penyebab | Tindakan |", "| Symptom | Cause | Action |"),
    ("| Area | Dokumentasi | Implementasi Go |", "| Area | Documentation | Go implementation |"),
    ("| File | Isi |", "| File | Contents |"),
    ("| # | File | Fitur | Status |", "| # | File | Feature | Status |"),
    ("| Komponen | Catatan |", "| Component | Notes |"),
    ("| Var | Default | Pengaruh |", "| Var | Default | Effect |"),
    ("| Item | Nilai |", "| Item | Value |"),
    ("| Table | Isi |", "| Table | Contents |"),
    ("Di-start dari", "Started from"),
    ("reload/restart via Go", "reload/restart via Go"),
    ("watchdog start ulang nginx jika mati", "watchdog restarts nginx if it dies"),
    ("Cron job renewal & manual run dikelola", "Cron renewal and manual runs are handled by"),
    ("bukan proses PHP terpisah.", "not a separate PHP process."),
    ("| Langkah |", "| Step |"),
    ("di nginx conf", "in nginx conf"),
    ("di-start dari", "started from"),
    ("di-stream via SSE", "streamed via SSE"),
    ("di jalankan", "runs"),
    ("di-enable", "enabled"),
    ("di-port", "ported"),
    ("di queue", "in queue"),
    ("di `/tmp/`", "in `/tmp/`"),
    ("listen di `LISTEN_ADDR`", "listens on `LISTEN_ADDR`"),
    ("dengan TLS opsional", "with optional TLS"),
    ("embed jika `FE_EMBED=true`", "embed when `FE_EMBED=true`"),
    ("HTTPS pada gosite", "HTTPS on gosite"),
    ("Serve `frontend/dist` dari binary", "Serve `frontend/dist` from binary"),
    ("gate `/api/v1/*` sebelum session", "gate `/api/v1/*` before session"),
    ("untuk upstream loopback", "for upstream loopback"),
    ("Konfigurasi relevan", "Relevant configuration"),
    ("Middleware di edge", "Edge middleware"),
    ("Detail URL dev/prod:", "Dev/prod URL details:"),
    ("Binary `proxy/main.go` menerima HTTPS di `:8080`, forward ke `http://localhost:8000` (PHP artisan).",
     "Binary `proxy/main.go` accepted HTTPS on `:8080`, forwarding to `http://localhost:8000` (PHP artisan)."),
    ("Digantikan oleh nginx reverse-proxy ke `gosite serve` + TLS langsung di Go.",
     "Replaced by nginx reverse-proxy to `gosite serve` + TLS directly in Go."),
    ("## Bagaimana nginx memuat site aktif", "## How nginx loads active sites"),
    ("Hanya file di `active.d/` yang dilayani sebagai vhost tambahan.",
     "Only files in `active.d/` are served as additional vhosts."),
    ("Toggle **memanggil `nginx reload`** (dengan test + auto-repair) — perbaikan dari legacy",
     "Toggle **calls `nginx reload`** (with test + auto-repair) — improvement over legacy"),
    ("untuk fallback jika config rusak", "for fallback when config is broken"),
    ("Layout filesystem SSL", "SSL filesystem layout"),
    ("Placeholder saat website create", "Placeholder on website create"),
    ("setelah certbot", "after certbot"),
    ("**Konflik umum:**", "**Common conflict:**"),
    ("sebagai file biasa", "as regular files"),
    ("memblokir Certbot karena", "blocks Certbot because"),
    ("sudah ada tetapi bukan lineage LE", "already exists but is not an LE lineage"),
    ("swap SSL ke default", "swap SSL to default"),
    ("hapus placeholder", "remove placeholder"),
    ("(sebelum job di-queue)", "(before job is queued)"),
    ("Agar `nginx -t` dan Certbot tidak gagal:", "So `nginx -t` and Certbot do not fail:"),
    ("Jika `ssl/live/{domain}/` berisi placeholder", "If `ssl/live/{domain}/` contains placeholder"),
    ("tanpa `fullchain.pem` LE", "without LE `fullchain.pem`"),
    ("Ganti `ssl_certificate` di `site.d`", "Replace `ssl_certificate` in `site.d`"),
    ("Hapus direktori", "Remove directory"),
    ("Baru enqueue Certbot — lineage LE bisa dibuat bersih",
     "Then enqueue Certbot — LE lineage can be created cleanly"),
    ("Tanpa langkah 2–3, menghapus placeholder saja membuat `nginx -t` gagal (cert path mengarah ke file yang tidak ada).",
     "Without steps 2–3, removing the placeholder alone makes `nginx -t` fail (cert path points to a missing file)."),
    ("Tanpa langkah 2–3, menghapus placeholder saja membuat `nginx -t` gagal (cert path mengarah ke file yang no).",
     "Without steps 2–3, removing the placeholder alone makes `nginx -t` fail (cert path points to a missing file)."),
    ("Sama dengan cron manual run", "Same as manual cron run"),
    ("alt site.d belum ada", "alt site.d missing"),
    ("WriteSiteConfig dengan ssl directives", "WriteSiteConfig with ssl directives"),
    ("overwrite path dari config", "overwrite paths from config"),
    ("Membaca path dari", "Read paths from"),
    ("load PEM dari disk, hitung expiry", "load PEM from disk, compute expiry"),
    ("## Renewal otomatis (cron default)", "## Automatic renewal (default cron)"),
    ("Dijalankan oleh cron scheduler Go", "Run by Go cron scheduler"),
    ("bukan Laravel queue.", "not Laravel queue."),
    ("## API ringkas", "## API summary"),
    ("(otomatis) atau hapus manual + jalankan certbot lagi", "(automatic) or manual delete + run certbot again"),
    ("Job tidak di-enqueue ke worker", "Job not enqueued to worker"),
    ("Pastikan build terbaru", "Ensure latest build"),
    ("`nginx -t` gagal sebelum certbot", "`nginx -t` fails before certbot"),
    ("Cert path mengarah ke file terhapus", "Cert path points to deleted file"),
    ("Cek `ssl_certificate` path di site.d sudah ke `fullchain.pem`",
     "Check `ssl_certificate` path in site.d points to `fullchain.pem`"),
    ("**Default roots:** `[\"/\"]` (seluruh filesystem container — production harus dibatasi via config)",
     "**Default roots:** `[\"/\"]` (entire container filesystem — restrict in production via config)"),
    ("**Paket:**", "**Package:**"),
    ("tolak ..", "reject `..`"),
    ("Baca teks", "Read text"),
    ("Simpan teks", "Save text"),
    ("Buat file/dir, upload multipart, import URL", "Create file/dir, multipart upload, URL import"),
    ("Hapus file/dir", "Delete file/dir"),
    ("Salin ke path tujuan", "Copy to destination path"),
    ("Jalankan script — hanya jika `FILES_ALLOW_EXECUTE=true`", "Run script — only when `FILES_ALLOW_EXECUTE=true`"),
    ("resolve path, tolak traversal di luar roots", "resolve path, reject traversal outside roots"),
    ("Execute dinonaktifkan default", "Execute disabled by default"),
    ("jika tool tersedia di host", "when tools are available on the host"),
    ("Setiap entry menyertakan:", "Each entry includes:"),
    ("## Kode", "## Code"),
    ("### Keamanan", "### Security"),
    ("Jika socket tidak tersedia → `NoopClient` (list kosong, tidak crash)",
     "When socket unavailable → `NoopClient` (empty list, no crash)"),
    ("`dockerinfra.NoopClient` dipakai saat `NewClient()` gagal (dev tanpa socket).",
     "`dockerinfra.NoopClient` is used when `NewClient()` fails (dev without socket)."),
    ("Aksi destruktif via **POST** (bukan GET legacy)", "Destructive actions via **POST** (not legacy GET)"),
    ("Container ID disanitize", "Container ID is sanitized"),
    ("**Validasi pre-flight:**", "**Pre-flight validation:**"),
    ("Note over NGX: tidak menulis site.d", "Note over NGX: does not write site.d"),
    ("Path auto (`/www/{slug}`) jika kosong", "Auto path (`/www/{slug}`) when empty"),
    ("### Validate — invariant penting", "### Validate — important invariant"),
    ("menjalankan `nginx -t` terisolasi **tanpa** menulis `site.d/`:",
     "runs isolated `nginx -t` **without** writing `site.d/`:"),
    ("Render config ke file temp di `/tmp/`", "Render config to temp file in `/tmp/`"),
    ("Ini mencegah validate \"menyimpan\" draft yang mengganggu save/reload berikutnya.",
     "This prevents validate from \"persisting\" a draft that breaks the next save/reload."),
    ("### Validasi bisnis", "### Business validation"),
    ("| Check | Kode error |", "| Check | Error code |"),
    ("Path di dalam web root", "Path inside web root"),
    ("Path adalah file", "Path is a file"),
    ("Proxy butuh upstream", "Proxy requires upstream"),
    ("Jika create dengan `active=true` gagal di `Reload`, service:",
     "If create with `active=true` fails at `Reload`, the service:"),
    ("hapus symlink `active.d`", "remove `active.d` symlink"),
    ("hapus `site.d`", "remove `site.d`"),
    ("`DELETE` baris DB", "`DELETE` DB row"),
    ("See diagram historis di git history; alur sama (validasi → DB → `Site::createConfig`) tanpa endpoint validate terpisah dan tanpa `nginx reload` otomatis pada semua path.",
     "See historical diagram in git history; same flow (validate → DB → `Site::createConfig`) without a separate validate endpoint and without automatic `nginx reload` on all paths."),
    ("**Penting:** penggantian include harus memakai path **absolut** ke file temp. Mengganti hanya bagian `site.d/*.conf` menghasilkan path invalid (`/storage/webconfig//tmp/...`).",
     "**Important:** include replacement must use an **absolute** path to the temp file. Replacing only the `site.d/*.conf` glob produces an invalid path (`/storage/webconfig//tmp/...`)."),
    ("Sama: test raw content di temp → write → reload.", "Same: test raw content in temp → write → reload."),
    ("Setiap `Reload()` memanggil `TestAndRepair` pada config produksi penuh sebelum `nginx -s reload`.",
     "Every `Reload()` calls `TestAndRepair` on the full production config before `nginx -s reload`."),
    ("Invariant: **test sebelum apply + rollback on failure** (update site config); **repair + test sebelum reload** (semua reload).",
     "Invariant: **test before apply + rollback on failure** (update site config); **repair + test before reload** (all reloads)."),
    ("### Yang dihapus", "### What is removed"),
    ("### Yang tidak dihapus otomatis", "### Not removed automatically"),
    ("### Urutan aman", "### Safe order"),
    ("vhost tidak lagi aktif", "vhost no longer active"),
    ("Biarkan folder `/www/...`, hapus config + DB saja", "Keep `/www/...` folder, remove config + DB only"),
    ("UI menampilkan konfirmasi sebelum delete.", "UI shows confirmation before delete."),
    ("Reload memakai [nginx auto-repair]", "Reload uses [nginx auto-repair]"),
    ("jika config lain rusak", "when other config is broken"),
    ("alt tidak ada", "alt missing"),
    ("Scheduler otomatis + manual run dengan **SSE stream**.", "Automatic scheduler + manual run with **SSE stream**."),
    ("Payload dijalankan sebagai shell command — pertimbangkan allowlist di produksi. Hanya user dengan session panel.",
     "Payload runs as a shell command — consider an allowlist in production. Panel session required."),
    ("GoSite hanya mengimplementasikan **update profil user**. Modul PHP/FPM legacy tidak di-port.",
     "GoSite only implements **user profile update**. Legacy PHP/FPM modules are not ported."),
    ("GoSite hanya mengimplementasikan **update profil user**. Module PHP/FPM legacy tidak ported.",
     "GoSite only implements **user profile update**. Legacy PHP/FPM modules are not ported."),
    ("Profil user saat ini dibaca via", "Current user profile is read via"),
    ("Password optional; jika diisi minimum 6 karakter", "Password optional; minimum 6 characters when set"),
    ("Device + dir required pada create/update", "Device + dir required on create/update"),
    ("Umount sebelum update/delete entry", "Umount before update/delete entry"),
    ("Entry JSON dapat menyertakan blok `s3` (endpoint, bucket, keys) — disimpan terpisah dari fstab line.",
     "Entry JSON may include an `s3` block (endpoint, bucket, keys) — stored separately from the fstab line."),
    ("Kredensial S3 (jika entry type s3fs)", "S3 credentials (for s3fs entry type)"),
    ("mount semua entry saat boot.", "mount all entries at boot."),
    ("Tail nginx access/error log per domain atau global.", "Tail nginx access/error log per domain or globally."),
    ("H-->>UI: [{ domain, name }] dari DB websites", "H-->>UI: [{ domain, name }] from DB websites"),
    ("Format `main` dari `config/nginx/custom.d/nginx-log.conf`.", "Format `main` from `config/nginx/custom.d/nginx-log.conf`."),
    ("aggregate traffic dari access log", "aggregate traffic from access log"),
    ("Admin tool **read-only** untuk SQLite panel.", "Admin tool **read-only** for panel SQLite."),
    ("tidak ada INSERT/UPDATE/DELETE dari UI", "no INSERT/UPDATE/DELETE from UI"),
    ("## Arsitektur", "## Architecture"),
    ("Saved queries di `saved_queries` untuk preset dashboard / ops",
     "Saved queries in `saved_queries` for dashboard / ops presets"),
    ("Frontend Logs view memakai `GET /query/meta` untuk source picker",
     "Frontend Logs view uses `GET /query/meta` for the source picker"),
    ("Pre-aggregated nginx traffic metrics untuk chart dashboard — menggantikan full-file scan `accessTraffic()` legacy.",
     "Pre-aggregated nginx traffic metrics for dashboard charts — replaces legacy full-file `accessTraffic()` scan."),
    ("Semua di `/api/v1/metrics/traffic/*` (session required):", "All under `/api/v1/metrics/traffic/*` (session required):"),
    ("`GET /dashboard` → `traffic_summary` dari `Summary(1h)`", "`GET /dashboard` → `traffic_summary` from `Summary(1h)`"),
    ("jika bucket belum terisi", "when buckets are empty"),
    ("## Paket", "## Packages"),
    ("| Path | Peran |", "| Path | Role |"),
    ("Tiga level konfigurasi nginx di GoSite.", "Three levels of nginx configuration in GoSite."),
    ("Svc->>NGX: TestConfig (temp file, tidak rewrite site.d)", "Svc->>NGX: TestConfig (temp file, no site.d rewrite)"),
    ("Konvensi usulan", "Proposed conventions"),
    ("Semua endpoint di bawah `/admin/*` legacy → butuh auth",
     "All legacy `/admin/*` endpoints → require auth"),
    ("Endpoint `/api/server/*` legacy **tanpa auth** — di GoSite **wajib** dilindungi auth",
     "Legacy `/api/server/*` endpoints were **unauthenticated** — in GoSite they **must** be protected"),
    ("Response login sukses:", "Successful login response:"),
    ("snapshot awal", "initial snapshot"),
    ("Validasi create/update", "Create/update validation"),
    ("Memvalidasi domain, path, upstream (proxy), duplikasi path",
     "Validates domain, path, upstream (proxy), path duplication"),
    ("Jika `active: true`, menjalankan `nginx -t` terisolasi pada config **rendered** (file temp, **tidak** menulis `site.d`)",
     "When `active: true`, runs isolated `nginx -t` on the **rendered** config (temp file, **does not** write `site.d`)"),
    ("endpoint terpisah atau inline", "separate endpoint or inline"),
    ("lihat detail di atas.", "see details above."),
    ("auto-fix aman", "safe auto-fix"),
    ("Dipanggil dari `config/start.sh` sebelum nginx + gosite serve.",
     "Invoked from `config/start.sh` before nginx + gosite serve."),
    ("baca default.conf", "read default.conf"),
    ("Setiap reload internal memanggil", "Every internal reload calls"),
    ("terlebih dahulu.", "first."),
    ("Endpoint yang butuh streaming / long-poll", "Endpoints that need streaming / long-poll"),
    ("Legacy memakai polling file `/tmp/*.txt` untuk output async:",
     "Legacy used `/tmp/*.txt` file polling for async output:"),
    ("event `done` saat selesai", "`done` event when finished"),
    ("Optional SSE untuk follow mode", "Optional SSE for follow mode"),
    ("Catatan keamanan migrasi", "Migration security notes"),
    ("Ubah semua `GET` yang menjalankan aksi", "Change all action `GET` routes"),
    ("Lindungi `/system/*` dengan auth (legacy terbuka)", "Protect `/system/*` with auth (legacy was open)"),
    ("validasi path ketat, deny di luar allowlist root", "strict path validation, deny outside allowlisted roots"),
    ("pertimbangkan allowlist atau approval untuk command berbahaya", "consider allowlist or approval for dangerous commands"),
    ("Entitas dan artefak", "Entities and filesystem"),
    ("Entitas database", "Database entities"),
    ("Artefak filesystem (bukan DB)", "Filesystem artifacts (not in DB)"),
    ("Relasi konseptual", "Conceptual relationships"),
    ("Validasi bisnis (harus dipertahankan)", "Business validation (must be preserved)"),
    ("Environment variables relevan", "Relevant environment variables"),
    ("Label tampilan", "Display label"),
    ("Config tambahan (jarang dipakai)", "Extra config (rarely used)"),
    ("symlink di active.d", "active.d symlink"),
    ("Terakhir dijalankan", "Last run"),
    ("Pesan gagal", "Failure message"),
    ("mis. domain", "e.g. domain"),
    ("migrations ada; dipakai minimal di legacy", "migrations exist; minimally used in legacy"),
    ("Certbot dan cron manual run memakai worker yang sama",
     "Certbot and manual cron runs share the same worker"),
    ("Vhost nginx per domain", "Per-domain nginx vhost"),
    ("symlink ke `site.d/`", "symlink to `site.d/`"),
    ("dibuat `gosite init`", "created by `gosite init`"),
    ("Certbot menolak membuat lineage jika `live/{domain}/` sudah ada sebagai placeholder Gosite. Service SSL menjalankan `prepareForCertbot` sebelum enqueue",
     "Certbot refuses to create a lineage when `live/{domain}/` already exists as a Gosite placeholder. The SSL service runs `prepareForCertbot` before enqueue"),
    ("Log nginx per domain", "Per-domain nginx logs"),
    ("Path unik | Tidak boleh dipakai website lain", "Unique path | Must not be used by another website"),
    ("Path aman | `Disk::validatePath()` — cegah traversal/illegal chars", "Safe path | `Disk::validatePath()` — block traversal/illegal chars"),
    ("Path bukan file | `is_file($path)` ditolak", "Path not a file | `is_file($path)` rejected"),
    ("Nginx config | `nginx -t` sebelum reload; rollback jika gagal", "Nginx config | `nginx -t` before reload; rollback on failure"),
    ("Detik idle sebelum lock", "Idle seconds before lock"),
    ("Email setiap aksi sensitif", "Email on sensitive actions"),
    ("Struktur paket (aktual)", "Actual package structure"),
    ("Kontrak REST", "REST contract"),
    ("Lapisan", "Layers"),
    ("business rules, validasi, orchestration", "business rules, validation, orchestration"),
    ("Status fase", "Phase status"),
    ("Fase 0 — Fondasi", "Phase 0 — Foundation"),
    ("Fase 1 — Website & nginx", "Phase 1 — Website & nginx"),
    ("Fase 2 — SSL & ops", "Phase 2 — SSL & ops"),
    ("Fase 3 — Advanced", "Phase 3 — Advanced"),
    ("Tidak di-port / deprecated", "Not ported / deprecated"),
    ("Tidak relevan tanpa PHP panel", "Not relevant without PHP panel"),
    ("Diganti `job_runs` + worker", "Replaced by `job_runs` + worker"),
    ("Kompatibilitas produksi", "Production compatibility"),
    ("Saat cutover:", "At cutover:"),
    ("Mount `./data` yang sama", "Mount the same `./data`"),
    ("Start gosite — baca", "Start gosite — reads"),
    ("Nginx config format **tidak berubah**", "Nginx config format **unchanged**"),
    ("Rollback: start bangunsite lama jika perlu", "Rollback: start legacy bangunsite if needed"),
    ("Testing per modul", "Per-module testing"),
    ("Setiap sequence → minimal:", "Each sequence should have at minimum:"),
    ("Unit test usecase (validasi, state transition)", "Unit tests for use cases (validation, state transitions)"),
    ("Integration test dengan tmp dir", "Integration tests with tmp dir"),
    ("Contract test API JSON schema", "API JSON schema contract tests"),
    ("Implementasi mengikuti topological order di atas.", "Implementation follows the topological order above."),
    ("Deploy image terbaru (`make up`) dan verifikasi stack produksi",
     "Deploy the latest image (`make up`) and verify the production stack"),
    ("Review [api-inventory.md]", "Review [api-inventory.md]"),
    ("vs implementasi handler", "against handler implementation"),
    ("Perbarui wiki via", "Update the wiki via"),
    ("setelah perubahan `docs/`", "after `docs/` changes"),
    ("Paket Go, fase implementasi, dependency", "Go packages, implementation phases, dependencies"),
    ("Sequence diagrams | ✅ 18 modul |", "Sequence diagrams | ✅ 18 modules |"),
    ("Struktur halaman wiki:", "Wiki page layout:"),
    ("Baca sequence modul yang relevan", "Read the relevant sequence module"),
    ("Cocokkan dengan", "Cross-check with"),
    ("dan `api/openapi.yaml`", "and `api/openapi.yaml`"),
    ("Auto-repair sebelum reload", "Auto-repair before reload"),
    ("(jika ada)", "(if any)"),
    ("Kapan dijalankan", "When it runs"),
    ("Strategi perbaikan", "Repair strategies"),
    ("Hubungan dengan", "Relationship with"),
    ("Keterangan", "Notes"),
    ("jarang dipakai", "rarely used"),
    ("Invariant produksi", "Production invariants"),
    ("Lihat ", "See "),
    ("lihat ", "see "),
    ("Untuk nginx/SSL:", "For nginx/SSL:"),
    ("Operasional server", "Server operations"),
    ("Runtime & infrastruktur", "Runtime & infrastructure"),
    ("Fitur", "Feature"),
    ("Modul", "Module"),
    ("Peran", "Role"),
    ("Isi", "Contents"),
    ("Dokumen pendukung migrasi", "Migration support documents"),
    ("Langkah disarankan", "Suggested steps"),
    ("Implementasi Go", "Go implementation"),
    ("Dokumentasi", "Documentation"),
    ("Paket Go", "Go packages"),
    ("fase implementasi", "implementation phases"),
    ("GoSite menjalankan", "GoSite runs"),
    ("sebelum setiap reload", "before every reload"),
    ("dan, jika gagal,", "and on failure,"),
    ("mencoba perbaikan otomatis yang aman", "applies safe automatic fixes"),
    ("berdasarkan pesan error", "based on error messages"),
    ("Ini mencegah", "This prevents"),
    ("meninggalkan nginx dalam keadaan config rusak", "leaving nginx with a broken config"),
    ("Semua pemanggil", "All callers of"),
    ("Alur reload:", "Reload flow:"),
    ("File yang boleh diperbaiki", "Files that may be repaired"),
    ("Hanya path di bawah prefix", "Only paths under prefixes"),
    ("diselesaikan ke", "resolve to"),
    ("symlink diselesaikan ke", "symlinks resolve to"),
    ("Pola error nginx", "nginx error pattern"),
    ("Perbaikan", "Fix"),
    ("Ganti ", "Replace "),
    ("Sisipkan directive", "Insert directive"),
    ("Komentari baris", "Comment out line"),
    ("Konflik listen", "listen conflict"),
    ("Dibuat di boot", "Created at boot"),
    ("jika belum ada", "if missing"),
    ("Batasan (sengaja)", "Intentional limits"),
    ("Tidak** memperbaiki", "Does **not** fix"),
    ("hanya mengomentari agar jejak tetap ada", "only comments lines to preserve history"),
    ("iterasi repair per satu pemanggilan", "repair iterations per call"),
    ("mencetak setiap aksi", "prints each action"),
    ("**tidak** menulis ke", "**does not** write to"),
    ("memakai file temporer", "uses temporary files"),
    ("Hapus file temp", "Delete temp files"),
    ("Tidak ada", "No"),
    ("tidak ada", "no"),
    ("Tidak** diubah", "**not** changed"),
    ("Cert hilang setelah hapus placeholder LE", "Cert missing after removing LE placeholder"),
    ("Directive modul tidak ter-load", "Directive module not loaded"),
    ("Variable tidak didefinisikan", "Variable not defined"),
    ("Directive di context salah", "Directive in wrong context"),
    ("brace tidak seimbang", "unbalanced braces"),
    ("Deploy the latest image (`make up`) dan verify the production stack",
     "Deploy the latest image (`make up`) and verify the production stack"),
    ("Proses saat container GoSite pertama kali (atau restart) dijalankan.",
     "What happens when the GoSite container starts (first boot or restart)."),
    ("Note over Repair: nginx -t + auto-fix aman", "Note over Repair: nginx -t + safe auto-fix"),
    ("watchdog start ulang nginx jika mati", "watchdog restarts nginx if it dies"),
    ("| Proses | Command | Catatan |", "| Process | Command | Notes |"),
    ("| Langkah | Output |", "| Step | Output |"),
    ("| Path publik | Handler | Catatan |", "| Public path | Handler | Notes |"),
    ("| Env | Default | Peran |", "| Env | Default | Role |"),
    ("| Paket | Peran |", "| Package | Role |"),
    ("| Task | Paket |", "| Task | Package |"),
    ("| File | Isi |", "| File | Contents |"),
    ("| Area | Dokumentasi | Implementasi Go |", "| Area | Documentation | Go implementation |"),
    ("| # | File | Fitur | Status |", "| # | File | Feature | Status |"),
    ("| Check | Kode error |", "| Check | Error code |"),
    ("| Gejala | Penyebab | Tindakan |", "| Symptom | Cause | Action |"),
    ("Template dari image → storage", "Templates from image → storage"),
    ("Struktur `/storage` kompatibel dengan deploy BangunSite lama",
     "`/storage` layout compatible with legacy BangunSite deploy"),
    ("path yang sama dipakai Certbot dan placeholder Gosite",
     "same path used by Certbot and Gosite placeholders"),
    ("alt tidak ada", "alt missing"),
    ("## Catatan", "## Notes"),
    ("tidak menulis site.d", "does not write site.d"),
    ("| `proxy` | Path auto (`/www/{slug}`) jika kosong |",
     "| `proxy` | Auto path (`/www/{slug}`) when empty |"),
    ("| Path adalah file | `PATH_IS_FILE` |", "| Path is a file | `PATH_IS_FILE` |"),
    ("See diagram historis di git history; alur sama (validasi → DB → `Site::createConfig`) tanpa endpoint validate terpisah dan tanpa `nginx reload` otomatis pada semua path.",
     "See historical diagram in git history; same flow (validate → DB → `Site::createConfig`) without a separate validate endpoint and without automatic `nginx reload` on all paths."),
    ("Frontend dapat memanggil endpoint granular untuk chart live:",
     "Frontend can call granular endpoints for live charts:"),
    ("Semua endpoint di grup **protected** — wajib session (+ basic auth jika enabled).",
     "All endpoints in the **protected** group require session (+ basic auth when enabled)."),
    ("Chart traffic memakai pre-aggregated buckets — lihat",
     "Chart traffic uses pre-aggregated buckets — see"),
    ("render Blade dengan nilai awal", "render Blade with initial values"),
    ("Session disimpan di SQLite (`sessions` table) dengan cookie HTTP-only.",
     "Session stored in SQLite (`sessions` table) with HTTP-only cookie."),
    ("Basic auth (jika enabled)", "Basic auth (when enabled)"),
    ("| `TLS_ENABLE` | `true` | HTTPS pada gosite |", "| `TLS_ENABLE` | `true` | HTTPS on gosite |"),
    ("| `FE_EMBED` | `false` | Serve `frontend/dist` dari binary |",
     "| `FE_EMBED` | `false` | Serve `frontend/dist` from binary |"),
    ("Svc->>NGX: TestConfig (temp file, tidak rewrite site.d)",
     "Svc->>NGX: TestConfig (temp file, no site.d rewrite)"),
    ("File test terisolasi:", "Isolated test file:"),
    ("hanya memuat satu vhost, tanpa `http.d/default.conf`.",
     "loads only one vhost, without `http.d/default.conf`."),
    ("swap SSL ke default", "swap SSL to default"),
    ("Tanpa langkah 2–3, mengremove placeholder saja membuat `nginx -t` gagal (cert path mengarah ke file yang no).",
     "Without steps 2–3, removing the placeholder alone makes `nginx -t` fail (cert path points to a missing file)."),
    ("WriteSiteConfig dengan ssl directives", "WriteSiteConfig with ssl directives"),
    ("overwrite path dari config", "overwrite paths from config"),
    ("| `CertStorageError: live directory exists` | Placeholder Gosite di `live/{domain}` | `prepareForCertbot` (otomatis) atau hapus manual + jalankan certbot lagi |",
     "| `CertStorageError: live directory exists` | Gosite placeholder in `live/{domain}` | `prepareForCertbot` (automatic) or manual delete + run certbot again |"),
    ("| Stream putus, `status=pending` | Job tidak di-enqueue ke worker | Pastikan build terbaru (fix `worker.Enqueue`) |",
     "| Stream drops, `status=pending` | Job not enqueued to worker | Ensure latest build (fix `worker.Enqueue`) |"),
    ("| `nginx -t` gagal sebelum certbot | Cert path mengarah ke file terhapus | `prepareForCertbot` swap ke default dulu |",
     "| `nginx -t` fails before certbot | Cert path points to deleted file | `prepareForCertbot` swap to default first |"),
    ("RemoveSiteConfig — hapus site.d", "RemoveSiteConfig — remove site.d"),
    ("| `false` / omitted | Biarkan folder `/www/...`, hapus config + DB saja |",
     "| `false` / omitted | Keep `/www/...` folder, remove config + DB only |"),
    ("Parse whitespace dari stdout `docker ps -a`", "Parse whitespace from stdout `docker ps -a`"),
    ("| GET | `/files/content?path=` | Baca teks |", "| GET | `/files/content?path=` | Read text |"),
    ("| `copy` | Salin ke path tujuan |", "| `copy` | Copy to destination path |"),
    ("| `execute` | Jalankan script — hanya jika `FILES_ALLOW_EXECUTE=true` |",
     "| `execute` | Run script — only when `FILES_ALLOW_EXECUTE=true` |"),
    ("untuk path di bawah `/www`", "for paths under `/www`"),
    ("GoSite hanya mengimplementasikan **update profil user**. Module PHP/FPM legacy tidak ported.",
     "GoSite only implements **user profile update**. Legacy PHP/FPM modules are not ported."),
    ("### Validasi", "### Validation"),
    ("## Legacy BangunSite (tidak ported)", "## Legacy BangunSite (not ported)"),
    ("## Legacy BangunSite (tidak di-port)", "## Legacy BangunSite (not ported)"),
    ("BangunSite legacy mengedit `/storage/php/*`. GoSite container tidak menjalankan PHP-FPM untuk panel.",
     "Legacy BangunSite edited `/storage/php/*`. GoSite container does not run PHP-FPM for the panel."),
    ("| `/storage/mount-secrets/` | Kredensial S3 (jika entry type s3fs) |",
     "| `/storage/mount-secrets/` | S3 credentials (for s3fs entry type) |"),
    ("<summary>GET untuk enable/delete</summary>", "<summary>GET for enable/delete</summary>"),
    ("Sama dengan Certbot —", "Same as Certbot —"),
    ("2. `sh -c {payload}` dengan streaming stdout/stderr",
     "2. `sh -c {payload}` with streaming stdout/stderr"),
    ("Payload dijalankan sebagai shell command", "Payload runs as a shell command"),
    ("Proses supervisor terpisah `crond`", "Separate supervisor `crond` process"),
    ("H-->>UI: [{ domain, name }] dari DB websites", "H-->>UI: [{ domain, name }] from DB websites"),
    ("Traffic view Preact memanggil series/top-sites/status-codes endpoints",
     "Traffic view Preact calls series/top-sites/status-codes endpoints"),
    ("Paket Go, fase implementasi, dependency", "Go packages, implementation phases, dependencies"),
    ("Sequence diagrams | ✅ 18 modul |", "Sequence diagrams | ✅ 18 modules |"),
    ("/etc/letsencrypt  →  symlink ke /storage/webconfig/ssl",
     "/etc/letsencrypt  →  symlink to /storage/webconfig/ssl"),
    ("| `ssl/archive/{domain}/` | Archive manual / certbot |",
     "| `ssl/archive/{domain}/` | Manual archive / certbot |"),
]

SKIP_PATTERNS = (
    re.compile(r"^```"),
    re.compile(r"^https?://"),
    re.compile(r"^POST /"),
    re.compile(r"^GET /"),
    re.compile(r"^PUT /"),
    re.compile(r"^DELETE /"),
    re.compile(r"^PATCH /"),
)


def fix_en_links(text: str) -> str:
    """Point English doc links to *.md, not *_id.md."""
    return re.sub(r"\]\(([^)]*)_id\.md\)", r"](\1.md)", text)


def translate_line(line: str) -> str:
    if any(p.match(line) for p in SKIP_PATTERNS):
        return line
    out = line
    for src, dst in REPLACEMENTS:
        out = out.replace(src, dst)
    return out


def translate_file(id_path: Path, en_path: Path) -> None:
    text = id_path.read_text(encoding="utf-8")
    lines = [translate_line(ln) for ln in text.splitlines(keepends=True)]
    en_path.write_text(fix_en_links("".join(lines)), encoding="utf-8")


def discover_targets(root: Path) -> list[Path]:
    if len(sys.argv) > 1:
        return [Path(p) for p in sys.argv[1:]]
    patterns = [
        "sequences/[0-9]*_id.md",
        "migration/backend-modules_id.md",
    ]
    targets: list[Path] = []
    for pat in patterns:
        targets.extend(sorted(root.glob(pat)))
    return targets


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    for id_path in discover_targets(root):
        if not id_path.name.endswith("_id.md"):
            continue
        en_path = id_path.with_name(id_path.name.replace("_id.md", ".md"))
        translate_file(id_path, en_path)
        print(en_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
